<?php
/*
 * Generated configuration file
 * Generated by: phpMyAdmin 4.0.4 setup script
 * Date: Thu, 20 Jun 2013 14:49:23 +0200
 */

/* Servers configuration */
$i = 0;

/* Server: sql44.modules [1] */
$i++;
$cfg['Servers'][$i]['verbose'] = 'sql44.modules';
$cfg['Servers'][$i]['host'] = 'sql44.modules';
$cfg['Servers'][$i]['port'] = '';
$cfg['Servers'][$i]['socket'] = '';
$cfg['Servers'][$i]['connect_type'] = 'tcp';
$cfg['Servers'][$i]['extension'] = 'mysql';
$cfg['Servers'][$i]['auth_type'] = 'config';
$cfg['Servers'][$i]['user'] = '4070769-1';
$cfg['Servers'][$i]['password'] = 't29qRXps';
$cfg['Servers'][$i]['only_db'] = '4070769-1';
/* End of servers configuration */

$cfg['blowfish_secret'] = '51c2f7a003ff78.45405789';
$cfg['DefaultLang'] = 'fr';
$cfg['ServerDefault'] = 1;
$cfg['UploadDir'] = '';
$cfg['SaveDir'] = '';
?>
